{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "0330acbf-6f0a-4a87-9834-e96d47c65cd0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading new loan applications from ../data/Credit-Project-Test-Data-file.csv...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\GOWTHAM\\AppData\\Local\\Temp\\ipykernel_27576\\4017931858.py:11: DtypeWarning: Columns (2,35,36) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  df = pd.read_csv(filepath)\n",
      "C:\\Users\\GOWTHAM\\AppData\\Local\\Temp\\ipykernel_27576\\4017931858.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.\n",
      "  df['pdate'] = pd.to_datetime(df['pdate'])\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading production pipeline from ../data/best_credit_pipeline.pkl...\n",
      "Scoring new applications...\n",
      "Applying strict risk threshold of 0.35...\n",
      "Success! Predictions generated for 150000 users.\n",
      "Report saved to: ../data/production_predictions.csv\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import argparse\n",
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# LOAD + CLEAN \n",
    "def load_and_clean_data(filepath):\n",
    "    \"\"\"Load new data for the pipeline.\"\"\"\n",
    "    print(f\"Loading new loan applications from {filepath}...\")\n",
    "    df = pd.read_csv(filepath) \n",
    "    \n",
    "    user_ids = df['msisdn'].copy()\n",
    "    df = df.drop('msisdn', axis=1)\n",
    "    \n",
    "\n",
    "    # 2. Date handling (Must match training script exactly)\n",
    "    df['pdate'] = pd.to_datetime(df['pdate'])\n",
    "    df['pMonth'] = df['pdate'].dt.month\n",
    "    df['pDay'] = df['pdate'].dt.day\n",
    "    df['pWeekday'] = df['pdate'].dt.weekday\n",
    "    df['isWeekend'] = (df['pdate'].dt.weekday >= 5).astype(int)\n",
    "    df = df.drop('pdate', axis=1)\n",
    "\n",
    "# 3. Ensure no leakage features sneaked into the production data\n",
    "    leakage_features = ['payback30', 'payback90', 'label']\n",
    "    df = df.drop(columns=leakage_features, errors='ignore')\n",
    "\n",
    "    return df, user_ids\n",
    "\n",
    "# PREDICTION ENGINE\n",
    "def predict(input_data_path, output_data_path, model_path, threshold=0.35):\n",
    "    \n",
    "    # 1. Load and prep data\n",
    "    X_new, user_ids = load_and_clean_data(input_data_path)\n",
    "    \n",
    "    # 2. Load the trained engine\n",
    "    print(f\"Loading production pipeline from {model_path}...\")\n",
    "    pipeline = joblib.load(model_path)\n",
    "    \n",
    "    # 3. Generate Probabilities\n",
    "    print(\"Scoring new applications...\")\n",
    "    risk_probabilities = pipeline.predict_proba(X_new)[:, 1]\n",
    "    \n",
    "    # 4. Apply Threshold (0.35)\n",
    "    print(f\"Applying strict risk threshold of {threshold}...\")\n",
    "    predictions = (risk_probabilities >= threshold).astype(int)\n",
    "    \n",
    "    # 5. Format the Business Report\n",
    "    results_df = pd.DataFrame({\n",
    "        \"Phone_Number_ID\": user_ids,\n",
    "        \"Risk_Probability\": np.round(risk_probabilities, 4),\n",
    "        \"Predicted_Class\": predictions,\n",
    "        \"Action\": np.where(predictions == 1, \"Approve\", \"Flag for Review\")\n",
    "    })\n",
    "    \n",
    "    # 6. Save the results\n",
    "    os.makedirs(os.path.dirname(output_data_path), exist_ok=True)\n",
    "    results_df.to_csv(output_data_path, index=False)\n",
    "    \n",
    "    print(f\"Success! Predictions generated for {len(results_df)} users.\")\n",
    "    print(f\"Report saved to: {output_data_path}\")\n",
    "\n",
    "def engineer_features(X):\n",
    "    \"\"\"Feature engineering used during training.\"\"\"\n",
    "\n",
    "    X_out = X.copy()\n",
    "\n",
    "    X_out[\"TotalLoanCount\"] = (\n",
    "        X_out[\"cnt_loans30\"] +\n",
    "        X_out[\"cnt_loans90\"]\n",
    "    )\n",
    "\n",
    "    X_out[\"AvgLoanAmount30\"] = np.where(\n",
    "        X_out[\"cnt_loans30\"] > 0,\n",
    "        X_out[\"amnt_loans30\"] /\n",
    "        X_out[\"cnt_loans30\"],\n",
    "        0\n",
    "    )\n",
    "\n",
    "    X_out[\"AvgLoanAmount90\"] = np.where(\n",
    "        X_out[\"cnt_loans90\"] > 0,\n",
    "        X_out[\"amnt_loans90\"] /\n",
    "        X_out[\"cnt_loans90\"],\n",
    "        0\n",
    "    )\n",
    "\n",
    "    return X_out\n",
    "\n",
    "# ENTRY POINT\n",
    "if __name__ == \"__main__\":\n",
    "    parser = argparse.ArgumentParser(description=\"Predict micro-credit loan defaults using the trained pipeline.\")\n",
    "    \n",
    "    parser.add_argument(\n",
    "        \"--input\", \n",
    "        type=str, \n",
    "        default=r\"../data/Credit-Project-Test-Data-file.csv\", \n",
    "        help=\"Path to new loan applications CSV\"\n",
    "    )\n",
    "    \n",
    "    parser.add_argument(\n",
    "        \"--output\", \n",
    "        type=str, \n",
    "        default=r\"../data/production_predictions.csv\", \n",
    "        help=\"Path to save the final business report\"\n",
    "    )\n",
    "    \n",
    "    parser.add_argument(\n",
    "        \"--model\", \n",
    "        type=str, \n",
    "        default=r\"../data/best_credit_pipeline.pkl\",\n",
    "        help=\"Path to the trained .pkl model\"\n",
    "    )\n",
    "    \n",
    "    # args=[] allows running safely in Jupyter Notebooks\n",
    "    args = parser.parse_args(args=[]) \n",
    "    \n",
    "    predict(\n",
    "        input_data_path=args.input, \n",
    "        output_data_path=args.output,\n",
    "        model_path=args.model\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "357c474b-e9ec-4db5-8302-3815022b9d31",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
