{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e55f8fee-fdb5-4740-a242-f241b267c5cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running 5-Fold Cross Validation...\n",
      "\n",
      "Mean CV ROC-AUC: 0.9324\n",
      "CV Std Dev:      0.0009\n",
      "\n",
      "Training Final Model...\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import argparse\n",
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.model_selection import train_test_split, cross_val_score\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.compose import ColumnTransformer, make_column_selector\n",
    "from sklearn.preprocessing import OneHotEncoder, FunctionTransformer\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score, precision_score, recall_score, f1_score\n",
    "\n",
    "# LOAD + CLEAN DATA\n",
    "def load_and_clean_data(filepath):\n",
    "    \"\"\"Load dataset and perform cleaning.\"\"\"\n",
    "    df = pd.read_csv(filepath).drop_duplicates()\n",
    "\n",
    "    # Removes unique identifier\n",
    "    df = df.drop('msisdn', axis=1, errors='ignore')\n",
    "\n",
    "    # Date handling\n",
    "    df['pdate'] = pd.to_datetime(df['pdate'])\n",
    "    df['pMonth'] = df['pdate'].dt.month\n",
    "    df['pDay'] = df['pdate'].dt.day\n",
    "    df['pWeekday'] = df['pdate'].dt.weekday\n",
    "    df['isWeekend'] = (df['pdate'].dt.weekday >= 5).astype(int)\n",
    "    df = df.drop('pdate', axis=1)\n",
    "\n",
    "    # Removes possible leakage features\n",
    "    leakage_features = ['payback30', 'payback90']\n",
    "    df = df.drop(columns=leakage_features, errors='ignore')\n",
    "\n",
    "    return df\n",
    "\n",
    "# FEATURE ENGINEERING\n",
    "def engineer_features(X):\n",
    "    X_out = X.copy()\n",
    "\n",
    "    # Total loan behavior\n",
    "    X_out[\"TotalLoanCount\"] = X_out[\"cnt_loans30\"] + X_out[\"cnt_loans90\"]\n",
    "\n",
    "    # Average loan amount\n",
    "    X_out[\"AvgLoanAmount30\"] = np.where(\n",
    "        X_out[\"cnt_loans30\"] > 0,\n",
    "        X_out[\"amnt_loans30\"] / X_out[\"cnt_loans30\"],\n",
    "        0\n",
    "    )\n",
    "\n",
    "    X_out[\"AvgLoanAmount90\"] = np.where(\n",
    "        X_out[\"cnt_loans90\"] > 0,\n",
    "        X_out[\"amnt_loans90\"] / X_out[\"cnt_loans90\"],\n",
    "        0\n",
    "    )\n",
    "\n",
    "    return X_out\n",
    "\n",
    "# PIPELINE\n",
    "def build_pipeline():\n",
    "    \"\"\"Preprocessing + model pipeline.\"\"\"\n",
    "    # Feature engineering step\n",
    "    feature_gen = FunctionTransformer(engineer_features)\n",
    "\n",
    "    # Numeric transformer (No scaling needed for Random Forest)\n",
    "    num_transformer = Pipeline(steps=[\n",
    "        ('imputer', SimpleImputer(strategy='median'))\n",
    "    ])\n",
    "\n",
    "    # Categorical transformer\n",
    "    cat_transformer = Pipeline(steps=[\n",
    "        ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),\n",
    "        ('encoder', OneHotEncoder(handle_unknown='ignore'))\n",
    "    ])\n",
    "\n",
    "    # Combined preprocessing\n",
    "    preprocessor = ColumnTransformer(transformers=[\n",
    "        ('num', num_transformer, make_column_selector(dtype_include=np.number)),\n",
    "        ('cat', cat_transformer, make_column_selector(dtype_exclude=np.number))\n",
    "    ])\n",
    "\n",
    "    # ML pipeline\n",
    "    pipeline = Pipeline(steps=[\n",
    "        ('feature_gen', feature_gen),\n",
    "        ('preprocessor', preprocessor),\n",
    "        ('classifier', RandomForestClassifier(\n",
    "            class_weight='balanced',\n",
    "            n_estimators=300,\n",
    "            min_samples_split=10,\n",
    "            max_depth=None,\n",
    "            random_state=42,\n",
    "            n_jobs=-1\n",
    "        ))\n",
    "    ])\n",
    "\n",
    "    return pipeline\n",
    "\n",
    "# EVALUATION\n",
    "def evaluate_model(model, X_val, y_val, threshold=0.35):\n",
    "    \"\"\"Evaluates trained model using a custom decision threshold.\"\"\"\n",
    "    # Probabilities\n",
    "    y_prob = model.predict_proba(X_val)[:, 1]\n",
    "\n",
    "    # Threshold tuning\n",
    "    y_pred = (y_prob >= threshold).astype(int)\n",
    "\n",
    "    # Print evaluation\n",
    "    print(\"\\nPRODUCTION MODEL EVALUATION\")\n",
    "    print(\"=\" * 60)\n",
    "    print(f\"Threshold Used: {threshold}\")\n",
    "    print(f\"\\nROC-AUC Score: {roc_auc_score(y_val, y_prob):.4f}\")\n",
    "    print(f\"PR-AUC Score:  {average_precision_score(y_val, y_prob):.4f}\")\n",
    "    print(f\"Precision:     {precision_score(y_val, y_pred):.4f}\")\n",
    "    print(f\"Recall:        {recall_score(y_val, y_pred):.4f}\")\n",
    "    print(f\"F1 Score:      {f1_score(y_val, y_pred):.4f}\")\n",
    "    \n",
    "    print(\"\\nConfusion Matrix:\")\n",
    "    print(confusion_matrix(y_val, y_pred))\n",
    "    \n",
    "    print(\"\\nClassification Report:\")\n",
    "    print(classification_report(y_val, y_pred))\n",
    "    print(\"=\" * 60 + \"\\n\")\n",
    "\n",
    "# FEATURE IMPORTANCE\n",
    "def show_feature_importance(model_pipeline):\n",
    "    \"\"\" Displays top feature importances dynamically extracted from the pipeline.\"\"\"\n",
    "    feature_names = model_pipeline.named_steps['preprocessor'].get_feature_names_out()\n",
    "    importances = model_pipeline.named_steps['classifier'].feature_importances_\n",
    "\n",
    "    importance_df = pd.DataFrame({\n",
    "        'Feature': feature_names,\n",
    "        'Importance': importances\n",
    "    }).sort_values(by='Importance', ascending=False)\n",
    "\n",
    "    print(\"\\nTOP 10 IMPORTANT FEATURES\")\n",
    "    print(\"=\" * 60)\n",
    "    print(importance_df.head(10))\n",
    "    print(\"=\" * 60 + \"\\n\")\n",
    "\n",
    "# MAIN\n",
    "def main(input_path, output_model_path):\n",
    "    # Load data\n",
    "    df = load_and_clean_data(input_path)\n",
    "\n",
    "    # Split features/target\n",
    "    X = df.drop(\"label\", axis=1)\n",
    "    y = df[\"label\"]\n",
    "\n",
    "    # CROSS VALIDATION\n",
    "    print(\"Running 5-Fold Cross Validation...\")\n",
    "    cv_pipeline = build_pipeline()\n",
    "    cv_scores = cross_val_score(cv_pipeline, X, y, cv=5, scoring='roc_auc', n_jobs=-1)\n",
    "    \n",
    "    print(f\"\\nMean CV ROC-AUC: {cv_scores.mean():.4f}\")\n",
    "    print(f\"CV Std Dev:      {cv_scores.std():.4f}\")\n",
    "\n",
    "    # TRAIN / VALIDATION SPLIT\n",
    "    X_train, X_val, y_train, y_val = train_test_split(\n",
    "        X, y, test_size=0.2, stratify=y, random_state=42\n",
    "    )\n",
    "\n",
    "    # Builds and trains final model\n",
    "    print(\"\\nTraining Final Model...\")\n",
    "    model_pipeline = build_pipeline()\n",
    "    model_pipeline.fit(X_train, y_train)\n",
    "\n",
    "    # Evaluates model\n",
    "    evaluate_model(model_pipeline, X_val, y_val, threshold=0.35)\n",
    "\n",
    "    # Feature importance\n",
    "    show_feature_importance(model_pipeline)\n",
    "\n",
    "    # SAVES MODEL\n",
    "    output_dir = os.path.dirname(output_model_path)\n",
    "    if output_dir:\n",
    "        os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "    joblib.dump(model_pipeline, output_model_path)\n",
    "    print(f\"\\nModel successfully saved to:\\n{output_model_path}\")\n",
    "\n",
    "# ENTRY POINT\n",
    "if __name__ == \"__main__\":\n",
    "    parser = argparse.ArgumentParser(description=\"Train Production-Grade Micro-credit Default Prediction Pipeline\")\n",
    "    parser.add_argument(\"--input\", type=str, default=r\"../data/Credit-Project-Train-Data-file.csv\", help=\"Path to training data\")\n",
    "    parser.add_argument(\"--output\", type=str, default=r\"../models/best_credit_pipeline.pkl\", help=\"Path to save model\")\n",
    "    \n",
    "    # args=[] allows running in Jupyter securely without crashing\n",
    "    args = parser.parse_args(args=[]) \n",
    "    main(input_path=args.input, output_model_path=args.output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6cc55301-2b3d-4296-8ddb-7e275a6b65df",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
